name: Hello
on: workflow_dispatch
jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, GitHub Actions!"
  say-goodbye:
    runs-on: ubuntu-latest
    needs: say-hi
    steps:
      - run: echo "Goodbye :("
